<?php

return [
    -12  => 'Kwajalein',
    -11  => 'Pacific/Midway',
    -10  => 'Pacific/Honolulu',
    -9   => 'America/Anchorage',
    -8   => 'America/Los_Angeles',
    -7   => 'America/Denver',
    -6   => 'America/Tegucigalpa',
    -5   => 'America/New_York',
    -4.5 => 'America/Caracas',
    -4   => 'America/Halifax',
    -3.5 => 'America/St_Johns',
    -3   => 'America/Argentina/Buenos_Aires',
    -3   => 'America/Sao_Paulo',
    -2   => 'Atlantic/South_Georgia',
    -1   => 'Atlantic/Azores',
    0    => 'Europe/London',
    1    => 'Europe/Belgrade',
    2    => 'Europe/Minsk',
    3    => 'Asia/Kuwait',
    3.5  => 'Asia/Tehran',
    4    => 'Asia/Muscat',
    5    => 'Asia/Yekaterinburg',
    5.5  => 'Asia/Kolkata',
    5.45 => 'Asia/Katmandu',
    6    => 'Asia/Dhaka',
    6.5  => 'Asia/Rangoon',
    7    => 'Asia/Krasnoyarsk',
    8    => 'Asia/Brunei',
    9    => 'Asia/Seoul',
    9.5  => 'Australia/Darwin',
    10   => 'Australia/Melbourne',
    11   => 'Asia/Magadan',
    12   => 'Pacific/Fiji',
    13   => 'Pacific/Tongatapu'
];